# Generated by Django 4.2.18 on 2025-01-16 10:44
# this is a new migrations file that was created when you typed the  python3 manage.py makemigrations command
# Django saw that your model had changed and that this change needed to be reflected in the database. The files are numbered sequentially, 
# and the filename gives you an idea of what each migration does without you having to read through the file. 
# Because each migration is numbered, you can reapply specific migrations if you wish.


from django.db import migrations, models


class Migration(migrations.Migration):
# dependencies list below contains tuples that consist of the app name, in this case blog and the migrations that must be applied before this one can be. 
# In our case, that is 0001_initial, the file we just looked at.
#  This dependency is logical because we cannot add a field to a model if the model does not yet exist.
    dependencies = [
        ('blog', '0001_initial'),
    ]
#The operations list then carries out the changes to the database. In this migration file, we are adding a field. We only have one operation in our list, 
# but if we were adding multiple fields or even another model, then they would appear here too
    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]

#makemigrations creates the migrations file locally, whereas the changes are applied to the database when you run the migrate command.
#We need to make migrations and migrate every time we change a database model.